### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by shama** [Jam3/gh-api-stream#3]
Am I doing this wrong? Or can errors not yet be handled?

If I do (a repo where `package.json` does not exist):

``` js
var res = api('/repos/shama/letswritecode/contents/package.json')
res.on('error', function () {
  // We got a 404 but we dont care
})
```

I still get the error:

``` shell

events.js:141
      throw er; // Unhandled 'error' event
            ^
GotError: GET https://api.github.com/repos/shama/letswritecode/contents/package.json response code is 404 (Not Found)
    at /Users/Kyle/Documents/www/liked/node_modules/gh-api-stream/node_modules/got/index.js:175:12
    at BufferStream.<anonymous> (/Users/Kyle/Documents/www/liked/node_modules/gh-api-stream/node_modules/got/node_modules/read-all-stream/index.js:64:3)
    at emitNone (events.js:72:20)
    at BufferStream.emit (events.js:166:7)
    at finishMaybe (/Users/Kyle/Documents/www/liked/node_modules/gh-api-stream/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/lib/_stream_writable.js:502:14)
    at endWritable (/Users/Kyle/Documents/www/liked/node_modules/gh-api-stream/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/lib/_stream_writable.js:512:3)
    at BufferStream.Writable.end (/Users/Kyle/Documents/www/liked/node_modules/gh-api-stream/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/lib/_stream_writable.js:477:5)
    at Unzip.onend (_stream_readable.js:486:10)
    at Unzip.g (events.js:260:16)
    at emitNone (events.js:72:20)
```

**Comment by mattdesl** [comment]
Ok, looks like I wasn't emitting the error event in streaming mode (rows: true).

Can you try again with latest patch? Here's a test:
https://github.com/Jam3/gh-api-stream/blob/master/test/errors.js

**Comment by shama** [comment]
Thanks! I updated and it looks like `.on('error', stream.emit.bind(stream, 'error'))` still isn't catching the 404 error. I'll dive in this evening and see if I can figure out why.

**Comment by shama** [comment]
Never mind! I had another stream wrapping the `api` that does the `ghauth`. I wasn't propagating the error, your fix works! Thanks a bunch!
